[package]
name = "sp-profiler"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
parking_lot = "0.10.0"
lazy_static = "1.4.0"
crossbeam = "0.7.3"
tracing = "0.1"
log = "0.4.8"
rental = "0.5.5"